blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/yairabramovitch/get-my-subtitle/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/yairabramovitch/get-my-subtitle/blob/main/README.md
    about: Read the project documentation

